# AppVeyor.com is a Continuous Integration service to build and run tests under Windows

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: https://stackoverflow.com/a/13751649
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\misc\\appveyor\\run_with_env.cmd"
    PYTHON: "C:\\conda"
    MINICONDA_VERSION: "latest"

  matrix:
    - PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"

platform:
  - x64

services:
  - mysql

install:
  # Install miniconda using a powershell script.
  - "powershell ./misc/appveyor/install-miniconda.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # Check that we have the expected version and architecture for Python
  - "%CMD_IN_ENV% python --version"
  # Install the build and runtime dependencies of the project.
  - "conda update -q --yes conda"
  # Create a conda environment using the astropy bonus packages
  - "conda create -q --yes -n test python=%PYTHON_VERSION%"
  - "activate test"
  # Install default dependencies
  - "conda install --yes -q pip"
  - "conda install --yes -q numpy==1.9.3 scipy matplotlib statsmodels pandas sqlalchemy"
  - "conda install --yes -q sphinx jinja2 flask pymysql click"
  - "conda install --yes -q traitsui>=4.4 traits lxml"
  - "conda install --yes -q -c obspy obspy"
  - "pip install flask-admin"
  - "pip install multiprocessing_logging"
  - "pip install markdown"
  - "pip install --trusted-host msnoise.org --use-wheel http://msnoise.org/test/scikits.samplerate-0.3.3-cp27-none-win_amd64.whl"
  # list package versions
  - "conda list"

# Not a .NET project, we build SunPy in the install step instead
build: false

test_script:
  - conda info --envs
  - "%CMD_IN_ENV% python setup.py develop"
  - echo %CD%
  - ps: mkdir test
  - ps: cd test
  - echo %CD%
  - msnoise bugreport -m
  - msnoise test
