name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - obspy
  - sqlalchemy
  - flask
  - flask-admin
  - scandir
  - logbook
  - pytables
  - click
  - pandas
  - folium
  - pip:
      - pyimgur
      - -e..
