name: Test suite on github actions

on: [push]

jobs:
  run_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: 'latest'
        python-version: ${{ matrix.python-version }}
        activate-environment: base
        environment-file: .github/environment.yml

    - name: print package info
      run: |
        conda info -a
        conda list

    - name: Install MSNoise
      run: |
        pip install -e .

    - name: Test suite
      run: |
        msnoise test
